eliminar <-  c("Shamanes Crew",
               "GIT",
               "Virus",
               "Rubio",
               "Sui Generis",
               "Pescado Rabioso",
               "2 minutos",
               "León Gieco",
               "Caramelos De Cianuro",
               "Miguel Mateos - Zas",
               "Serú Girán",
               "Sumo",
               "Alejandro Lerner",
               "GUFI",
               "Invisible",
               "Generación 12",
               "Almendra",
               "Ella Baila Sola",
               "Porcupine Tree",
               "Mikel Erentxun",
               "Beatriz Luengo",
               "Fidel Nadal",
               "King Crimson",
               "Christina y Los Subterraneos",
               "Nonpalidece",
               "Carlos Santana",
               "Miguel Mateos",
               "Warcry",
               "Ely Guerra",
               "Onda Vaga",
               "Stratovarius",
               "John Frusciante",
               "Luca Bocci",
               "Death",
               "Azucar Moreno",
               "Illya Kuryaki & The Valderramas",
               "We Are The Grand",
               "Usted Señalemelo",
               "TWICE",
               "Flema",
               "Debbie Gibson",
               "Temple Of The Dog",
               "Su Presencia",
               "Lisandro Aristimuño",
               "Piero",
               "Candlebox",
               "La Húngara",
               "Suede",
               "Albert Hammond",
               "Cerati-Melero",
               "Cabas",
               "Roger Waters",
               "Steven Wilson",
               "Grand Funk Railroad",
               "Velvet Revolver",
               "Esteman",
               "Kameleba",
               "Lobo",
               "Tan Bionica",
               "Dorian",
               "Los Ladrones Sueltos",
               "Mi Sobrino Memo",
               "Fondo Flamenco",
               "Tierra Santa",
               "La Vida Bohème",
               "Kike Pavón",
               "Ingrid Rosario",
               "The Skatalites",
               "David Lebón",
               "Las Ligas Menores",
               "Daniela Spalla",
               "Kreator",
               "The Mars Volta",
               "Memphis La Blusera",
               "Bad English",
               "Brenda Lee",
               "frederic",
               "boom boom kid",
               "Testament",
               "Joe Satriani",
               "Survive Said The Prophet",
               "Los Espiritus",
               "Bruce Dickinson",
               "Laguna Pai",
               "Emmanuel Horvilleur",
               "John Waite",
               "amazarashi",
               "Accept",
               "Saurom",
               "Eva Ayllón",
               "Blest",
               "Mancha De Rolando",
               "La Secta AllStar",
               "Armonia 10",
               "Gilbert O'Sullivan",
               "Perras on the beach",
               "Juan Ingaramo",
               "Cock Robin",
               "Tranzas",
               "Lisa Stansfield",
               "Los Mesoneros",
               "Rojo",
               "Queensrÿche",
               "Manowar",
               "Bedroom",
               "Barry Gibb",
               "Alton Ellis",
               "Richard Ashcroft",
               "Alannah Myles", 
               "Robert Plant",
               "Christina Rosenvinge",
               "Avalanch",
               "Hello Sleepwalkers",
               "Dancing Mood", 
               "Player",
               "Delirious",
               "Bill Haley & His Comets", 
               "Chubby Checker", 
               "Eskorbuto",
               "Fear, and Loathing in Las Vegas",
               "Jim Morrison", 
               "Mad Season",
               "Benny Mardones",
               "Mr. Bungle",
               "Palito Ortega", 
               "Capleton",
               "Los Caballeros De La Quema",
               "Grupo Nectar",
               "Kinky",
               "Conociendo Rusia",
               "Pappo's Blues",
               "Pappo",
               "Morphine",
               "Banda XXI",
               "kankakupiero",
               "Los Violadores",
               "Coque Malla",
               "Resistencia Suburbana",
               "Ambrosia",
               "Mano Negra",
               "Bandalos Chinos",
               "Lucho Barrios",
               "Reincidentes",
               "Procol Harum",
               "Indios",
               "Las manos de Filippi",
               "Fabiana Cantilo",
               "Paula Abdul")
